// src/utils/fontawesome.js
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import {
  faEye,
  faUsers,
  faShoppingCart,
  faDollarSign,
  faArrowUp,
  faArrowDown,
  faChartLine,
  faCog,
  faHome,
  faBell,
  faUserPlus,
  faTrash,
  faEdit,
  faSearch,
  faTimes,
  faQuestionCircle,
  faPlus,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faBars,
  faSun,
  faMoon,
  faUser,
  faUserSlash,
  faSignOutAlt,
  faEllipsisV,
  faSpinner,
  faInbox,
  faBox,
  faDownload,
  faEnvelope,
  faPhone,
  faComments,
  faArrowRight,
  faBook,
  faVideo,
  faLifeRing,
  faTachometerAlt,
  faKey,
  faPercentage,
  faSort,
  faFileAlt
} from '@fortawesome/free-solid-svg-icons'

// 添加项目实际使用的图标到库中
library.add(
  faEye,
  faUsers,
  faShoppingCart,
  faDollarSign,
  faArrowUp,
  faArrowDown,
  faChartLine,
  faCog,
  faHome,
  faBell,
  faUserPlus,
  faTrash,
  faEdit,
  faSearch,
  faTimes,
  faQuestionCircle,
  faPlus,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faBars,
  faSun,
  faMoon,
  faUser,
  faUserSlash,
  faSignOutAlt,
  faEllipsisV,
  faSpinner,
  faInbox,
  faBox,
  faDownload,
  faEnvelope,
  faPhone,
  faComments,
  faArrowRight,
  faBook,
  faVideo,
  faLifeRing,
  faTachometerAlt,
  faKey,
  faPercentage,
  faSort,
  faFileAlt
)

export { FontAwesomeIcon }
